apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedodo-deployment
  namespace: dev-fedodo
spec:
  selector:
    matchLabels:
      app: fedodo
  template:
    metadata:
      labels:
        app: fedodo
    spec:
      containers:
        - name: fedodo
          image: fedodo/fedodo.server:dev_16
          imagePullPolicy: Always
          resources:
            limits:
              memory: "500Mi"
              cpu: "1m"
          ports:
            - containerPort: 80
              name: port-http
          env:
            - name: DOMAINNAME
              value: "dev.fedodo.social"
            - name: MONGO_HOSTNAME
              value: "cluster0.mnp03hj.mongodb.net"
            - name: MONGO_USERNAME
              value: "root"
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fedodo-secrets
                  key: mongodb-password
            - name: API_ENCRYPTION_CERT
              valueFrom:
                secretKeyRef:
                  name: fedodo-certs
                  key: fedodo-encryption
            - name: API_SIGNING_CERT
              valueFrom:
                secretKeyRef:
                  name: fedodo-certs
                  key: fedodo-signing

---
apiVersion: v1
kind: Service
metadata:
  name: fedodo-service
  namespace: dev-fedodo
spec:
  selector:
    app: fedodo
  ports:
    - port: 80
      targetPort: port-http
      name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fedodo-ingress
  namespace: dev-fedodo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-redirectscheme@kubernetescrd
spec:
  tls:
    - hosts:
        - "dev.fedodo.social"
      secretName: fedodo-cert
  rules:
    - host: dev.fedodo.social
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fedodo-service
                port:
                  number: 80
#
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ap-redirection-ingress
#  annotations:
#    cert-manager.io/cluster-issuer: letsencrypt
#    traefik.ingress.kubernetes.io/router.entrypoints: websecure
#    traefik.ingress.kubernetes.io/router.middlewares: default-redirectschemefipv@kubernetescrd
#spec:
#  tls:
#    - hosts:
#        - "xn--fachinformatiker-prfungsvorbereitung-w0d.de"
#      secretName: ap-cert-fipv
#  rules:
#    - host: xn--fachinformatiker-prfungsvorbereitung-w0d.de
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: ap-service
#                port:
#                  number: 80
#    - host: fi.lna-dev.net
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: ap-service
#                port:
#                  number: 80
#
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ap-redirection-ingress-http
#  annotations:
#    traefik.ingress.kubernetes.io/router.entrypoints: web
#    traefik.ingress.kubernetes.io/router.middlewares: default-redirectschemefipv@kubernetescrd
#spec:
#  rules:
#    - host: xn--fachinformatiker-prfungsvorbereitung-w0d.de
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: ap-service
#                port:
#                  number: 80
#    - host: fi.lna-dev.net
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: ap-service
#                port:
#                  number: 80

---
# Needed because of HTTP to HTTPS redirecting
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fedodo-ingress-http
  namespace: dev-fedodo
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-redirectscheme@kubernetescrd
spec:
  rules:
    - host: dev.fedodo.social
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fedodo-service
                port:
                  number: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirectscheme
  namespace: dev-fedodo
spec:
  redirectRegex:
    regex: '^https?://(?:www\.)?(.+)'
    replacement: "https://${1}"
    permanent: true
#
#---
#apiVersion: traefik.containo.us/v1alpha1
#kind: Middleware
#metadata:
#  name: redirectschemefipv
#spec:
#  redirectRegex:
#    regex: '.*'
#    replacement: "https://fachinformatikerpruefungsvorbereitung.de"
#    permanent: true