name: Docker Image CI

on:
  push:
    branches: [ master ]
    
jobs:
  RunTests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: Fedodo/Fedodo.Pipelines/BuildContainer.NET@main
        with:
          TAG_PREFIX: ""
          PROJECT_PATH: "Fedodo.BE.ActivityPub.Test/Fedodo.BE.ActivityPub.Test.csproj"
          DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
          REPO: "fedodo.be.activitypub"