name: Docker Image CI

on:
  push:
    branches: [ master ]

env:
  DOCKERHUB_USERNAME: "fedodo"
  PROJECT_PATH: "Fedodo.Server.Test/Fedodo.Server.Test.csproj"
  VERSION: 0.1.${{ github.run_number }}

jobs:
  RunTests:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Test
      - name: "Install .net"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.x"

      - name: "Restore packages"
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: "Test"
        run: dotnet test ${{ env.PROJECT_PATH }} --no-restore --configuration Release

  ReleaseVersion:
    runs-on: ubuntu-latest
    needs: [ "RunTests" ]
    
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Build
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.DOCKERHUB_USERNAME }}/fedodo.server:${{ env.VERSION }}

      # Publish
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the image to dockerhub
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/fedodo.server:${{ env.VERSION }}
  
  ReleaseLatest:
    runs-on: ubuntu-latest
    needs: [ "RunTests" ]
    
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Build
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.DOCKERHUB_USERNAME }}/fedodo.server:latest

      # Publish
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the image to dockerhub
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/fedodo.server:latest