name: Docker DEV Image CI

on:
  workflow_dispatch:
  
  push:
    branches: [ dev ]

env:
  DOCKERHUB_USERNAME: "fedodo"
  PROJECT_PATH: "Fedodo.BE.ActivityPub.Test/Fedodo.BE.ActivityPub.Test.csproj"

jobs:

  ReleaseVersion:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # Test
      - name: "Install .net"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.x"

      - name: "Restore packages"
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: "Test"
        run: dotnet test ${{ env.PROJECT_PATH }} --no-restore --configuration Release

      # Build
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.DOCKERHUB_USERNAME }}/fedodo.be.activitypub:dev_${{ github.run_number }}

      # Publish
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the image to dockerhub
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/fedodo.be.activitypub:dev_${{ github.run_number }}
  
  PublishVersion:
    runs-on: ubuntu-latest
    needs: [ "ReleaseVersion" ]

    steps:
      # Download Secure-File
      - name: base64-to-file
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: "custom-config"
          encodedString: ${{ secrets.KUBECTL_CONFIG }}
      
      # Checkout
      - uses: actions/checkout@v3

      # Deploy to Kubernetes
      - run: helm upgrade fedodo oci://registry-1.docker.io/fedodo/fedodo.chart --values ./Kubernetes/values.yaml --kubeconfig ${{ steps.write_file.outputs.filePath }} --set microservices.fedodo_be_activitypub.version=${{ env.DOCKERHUB_USERNAME }}/fedodo.be.activitypub:dev_${{ github.run_number }}
